export const imgUrls= [
  {
    id:1,
    url:'https://tinyurl.com/2s49hhyb'   
  },
  {
    id:48,
    url:'https://tinyurl.com/5b5ec4p9',
  },
  {
    id:2,
    url:'https://tinyurl.com/mj9umrjf',
  },
  {
   id:5,
   url:'https://tinyurl.com/6ttw7hpp',
  },
  {
   id:6,
   url:'https://tinyurl.com/2p93f73t',
  },
  {
   id:7,
   url:'https://tinyurl.com/3b6em5s9',
  },
  {
   id:8,
   url:'https://tinyurl.com/4k4wy6pv',
  },
  {
   id:10,
   url:'https://tinyurl.com/5853tvav',
  },
  {
   id:11,
   url:'https://tinyurl.com/y39kp3zp',
  },
  {
   id:12,
   url:'https://tinyurl.com/4262zp6k' 
  },
  {
   id:13,
   url:'https://tinyurl.com/y39kp3zp' 
  },
  {
   id:15,
   url:'https://tinyurl.com/2rptaycx' 
  },
  {
   id:16,
   url:'https://tinyurl.com/yu299hur' 
  },
  {
   id:18,
   url:'https://tinyurl.com/3ep5pav8' 
  },
  {
   id:19,
   url:'https://tinyurl.com/3xadtjn4' 
  },
  {
   id:21,
   url:'https://tinyurl.com/466mfwke' 
  },
  {
   id:22,
   url:'https://tinyurl.com/3nnmjzbm' 
  },
  {
   id:23,
   url:'https://tinyurl.com/2p8s9m44' 
  },
  {
   id:24,
   url:'https://tinyurl.com/yc73dpt4' 
  },
  {
   id:25,
   url:'https://tinyurl.com/ycxt8nme' 
  },
  {
   id:26,
   url:'https://tinyurl.com/yc6ddpfa' 
  },
  {
   id:27,
   url:'https://tinyurl.com/mryh2kxb' 
  },
  {
   id:28,
   url:'https://tinyurl.com/4snsnvnf' 
  },
  {
   id:29,
   url:'https://tinyurl.com/bdz9x6bh' 
  },
  {
   id:30,
   url:'https://tinyurl.com/32k7napp' 
  },
  {
   id:31,
   url:'https://tinyurl.com/243xuuup' 
  },
  {
   id:32,
   url:'https://tinyurl.com/2p8wk38s' 
  },
  {
   id:33,
   url:'https://tinyurl.com/4jvdnerd' 
  },
  {
   id:34,
   url:'https://tinyurl.com/3nmwvwmb' 
  },
  {
   id:35,
   url:'https://tinyurl.com/nha5kmuh' 
  },
  {
   id:36,
   url:'https://tinyurl.com/2kp27498' 
  },
  {
   id:37,
   url:'https://tinyurl.com/yckwtjf3' 
  },
  {
   id:38,
   url:'https://tinyurl.com/26sn759p' 
  },
  {
   id:39,
   url:'https://tinyurl.com/yk9dp4ch' 
  },
  {
   id:40,
   url:'https://tinyurl.com/mr88c3af' 
  },
  {
   id:41,
   url:'https://tinyurl.com/2x664zw8' 
  },
  {
   id:42,
   url:'https://tinyurl.com/4uc7v8ph' 
  },
  {
   id:43,
   url:'https://tinyurl.com/yv8da49w' 
  },
  {
   id:44,
   url:'https://tinyurl.com/ykzdkm52' 
  },
  {
   id:45,
   url:'https://tinyurl.com/2vaskajf' 
  },
  {
   id:46,
   url:'https://tinyurl.com/4mdb9436' 
  },
  {
   id:47,
   url:'https://tinyurl.com/4snsnvnf' 
  },
]